### PR TITLE
Rathur1 patch 1

### PR DESCRIPTION
**Pull request by RATHUR1**

### CODE REVIEW

**Comment by danmindru** [comment]
hey @RATHUR1 please add the changes to the readme file, you've created 2 new text files :)

**Comment by RATHUR1** [comment]
Thanks Dan,I have no idea what I'm doing RE: githubRic--Sent with mail.com Mail appOn 20/11/2024, 21:20 Dan Mindru ***@***.***> wrote:

hey @RATHUR1 please add the changes to the readme file, you've created 2 new text files :)

**Comment by danmindru** [comment]
haha no worries, just give me 2 categories for these then and I'll get them in :D

**Comment by RATHUR1** [comment]
Thanks. IndieEarnr is Affiliate Marketing and Fuelance  is Freelancing
 

Sent: Wednesday, November 20, 2024 at 9:53 PM

**Pull request closed without merging**
